# Generated by Django 2.2.5 on 2019-09-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notice',
            new_name='notices',
        ),
    ]
