# Generated by Django 2.2.5 on 2019-09-13 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_login_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='Date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
